### PR TITLE
341 goal imp

### PR DESCRIPTION
**Pull request by nelealbers**
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/341 using conditional response variations.

### CODE REVIEW

**Comment by nelealbers** [comment]
@bscheltinga Ah I see, that is not what we had in Beyza's dialog that was the basis of the dialog, so I did not even think that it would be an option. In that case conditional response variations won't work.

**Comment by bscheltinga** [comment]
Yes, I figured out that a conditional response would not work. I think we have two options now:
1. Keep it as it is
2. Make the response generic

With generic response I mean the following, currently we have:
>   utter_ask_why_pa_goal_important_nuance:
>     - text: "Ik kan me voorstellen dat jouw {why_pa_goal_important_values} belangrijk voor je is/zijn. Kun je me iets
>             meer vertellen over waarom dit doel belangrijk is voor jouw {why_pa_goal_important_values}?"

We can change that into:

>   utter_ask_why_pa_goal_important_nuance:
>     - text: "Ik kan me voorstellen dat dit belangrijk voor je is. Kun je me vertellen waarom je dit hebt gekozen?"

**Comment by nelealbers** [comment]
@bscheltinga I was at a conference so just looked at it now. I think the actual problem is that the implementation assumes that people can type multiple numbers for their goal importance. But this is not the case - the user should just type one. The goal importance comes from Beyza's dialog, where people can only choose one. And the excel-file for the goal-setting dialog also does not say anything about being able to choose multiple answers.

**Comment by bscheltinga** [comment]
@nelealbers I fixed the validation and added the sentence that they need to choose the option which is most important for them: "Kies de optie die voor jouw het belangrijkste is."

**Comment by bscheltinga** [comment]
@nelealbers you're right. I retrained the model.

**Comment by nelealbers** [comment]
@bscheltinga Nice, I merged it!

**Pull request merged**
