### PR TITLE
371 fix date format goal setting

### PR DESCRIPTION
**Pull request by bscheltinga**
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/371

### CODE REVIEW

**Comment by bscheltinga** [comment]
I was not able to test it.. Apparently /EXTERNAL_trigger_goal_setting was not working...

**Comment by bscheltinga** [comment]
With testing, I have a problem with storing the date to db. The line
selected = session.query(Users).filter_by(nicedayuid=user_id).one()
is not working, probably because my user_id is not in the db? It's not working both at this branch as on the main branch

**Comment by wbaccinelli** [comment]
> With testing, I have a problem with storing the date to db. The line selected = session.query(Users).filter_by(nicedayuid=user_id).one() is not working, probably because my user_id is not in the db? It's not working both at this branch as on the main branch

Yes, if the user is not in the `users` table, then this will fail. Are you sure that this is the case?

**Review by wbaccinelli — APPROVED** [review]
Looks good! One small comment: make sure to merge the latest version of the main and to retrain the model before merging. Otherwise the model is not up to date with the contents.

**Pull request merged**
