### PR TITLE
Fix spelling error

### PR DESCRIPTION
**Pull request by bscheltinga**
Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/399

### CODE REVIEW

**Review by nelealbers — APPROVED** [review]
I see you mastered this extremely difficult issue very well :D.

**Comment by bscheltinga** [comment]
> I see you mastered this extremely difficult issue very well :D.

Thank you. I'd like to thank @wbaccinelli and @svenvanderburg for teaching me a lot of skills in the world of programming. Without you, this wouldn't have been possible. Thanks guys!

**Comment by wbaccinelli** [comment]
> > I see you mastered this extremely difficult issue very well :D.
> 
> Thank you. I'd like to thank @wbaccinelli and @svenvanderburg for teaching me a lot of skills in the world of programming. Without you, this wouldn't have been possible. Thanks guys!

Congrats @bscheltinga, I cannot describe the satisfaction I get in seeing that the student surpassed the teachers.

**Comment by svenvanderburg** [comment]
I am extremely proud of you @bscheltinga, I already knew you were brilliant, but I would never have expected you to come so far! #so-proud🥇

**Pull request merged**
